version: '3'
services:
    server:
        build: ./fcgi_server/
    proxy-nginx:
        image: nginx
        ports:
            - 80:8080
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
